### ISSUE TITLE
No payload.before or url in old (< 2015) PushEvents in githubarchive on BigQuery

### ISSUE THREAD

**Issue by bburky** [igrigorik/githubarchive.org#146] opened 2016-07-01 00:50 UTC
I'm wanting to find what the old HEAD was for PushEvents using Google BigQuery.

Events after 2015-01-01 include a `payload.before` field that includes this. Old commits (prior to 2015-01-01) don't have this field. However, old commits instead have a `url` field of the form `https://github.com/user/repo/compare/0000000000...ffffffffff` which can be parsed to recover the same value (though truncated to 10 characters).

Until recently the `url` field was a column in both [githubarchive:year.20xx] and [githubarchive:github.timeline] and I could use it fine. It recently disappeared. Could you please add this data back to the Google BigQuery dataset?

If you're doing any dataset normalization before uploading to BigQuery, you might want to parse the old sha1 from the `url` field of <2015 PushEvent and inject it into the payload as `payload.before`. Or just add the whole `url` field back as a column in BigQuery.

(A side note, now that I would have to query the whole `payload` column in BigQuery, this is a very expensive query. Previously I could just get the value I wanted from the `url` column. This is a ~1TB query instead of a few GB. I'm not entirely sure what the value of BigQuery is now that you've combined all the data into one `payload` column.)

**Comment by igrigorik** [comment] 2016-07-01 15:43
We normalized the dataset between 2011-2015.. so, all pre 2015 events have same top-level structure and all remaining fields are within the `payload` (JSON field). You should be able to extract the field you're looking for from that via JSON_EXTRACT.

**Comment by bburky** [comment] 2016-07-02 14:52
No, the data I'm looking for isn't there. If you look at PushEvent events from 2014-01-01-1.json.gz, the payload only contains `sha`, `size`, `ref`, and `head` in the top level `payload`. The problem is the `url` field is another top level field and is not present in the BigQuery data.

If you look at https://bigquery.cloud.google.com/table/githubarchive:day.20140101 and use the preview option to look at some PushEvent records, you will see that the payload column matches the `payload` field from the json.gz file exactly, and the `url` value is no where to be found. It is not in the `other` column either.


---

All that said, I realized there's a second way I can recover this data. I should be able to query BigQuery for all PushEvents and then use window functions to group each push event with the previous PushEvent for the same repo, user and ref. The LAG() function should be able to return the previous value. (This assumes there are no missing push events in the archive, actually preserving `url` field the data would avoid any missing data problems.)

**Comment by igrigorik** [comment] 2016-07-02 20:18
@bburky hmm, interesting. For this particular case, that field should have been pushed into "other" string field. Except, I don't see it.. @arfon, did we miss this one?

**Comment by arfon** [comment] 2016-07-03 03:22
> @bburky hmm, interesting. For this particular case, that field should have been pushed into "other" string field. Except, I don't see it.. @arfon, did we miss this one?

Yeah, looks like we did 😞 . @igrigorik - it's straightforward for me to regenerate the transformed files again to be imported into the `githubarchive` tables (and I don't think this field is present anymore so isn't an issue for newer events).

Shall I go ahead and re-process the older files or would it be better to just have a smaller set of `event_id => url` mappings so that you can update the tables in place?

Also, thinking about it, this issue was caused by me writing [this method](https://github.com/arfon/gh_archive_parser/blob/master/event_transform.rb#L50-L65) pretty stupidly as I've essentially got the schema hard coded in here (for the top level fields). I'll try and look at improving that.

**Comment by igrigorik** [comment] 2016-07-03 06:48
> Shall I go ahead and re-process the older files or would it be better to just have a smaller set of event_id => url mappings so that you can update the tables in place?

The former, we can just overwrite the pre 2015 tables once over.

**Comment by arfon** [comment] 2016-07-03 15:27
> The former, we can just overwrite the pre 2015 tables once over.

@igrigorik - OK, I've started these processing this morning. I'm about to head out on holiday for a week and so will try and find some internet access during my trip to upload these when they're processed.

@bburky sorry about this!

**Comment by bburky** [comment] 2016-07-03 17:02
Great, glad you figured it out. I'll wait for the data to be updated.

**Comment by arfon** [comment] 2016-07-07 22:40
@igrigorik - I'm uploading the re-generated files to `gs://githubarchive-bigquery/transformed-part-deux/`. These should all be there in < 24 hrs.

I processed all years but I'm pretty sure that this top-level `url` field is only present in the `PushEvents` for pre-2015 data.

Perhaps you could share some links to some of these files from the `githubarchive-bigquery` bucket once these have been uploaded so that @bburky can confirm these are looking better? (I'm currently on very spotty internet in rural Canada 🍁 and so would have done this myself otherwise)

**Comment by arfon** [comment] 2016-07-11 13:36
OK, @bburky - could you take a look at the attached file? This now has the `url` persisted in the `other` field: [2014-01-01-1.json.gz](https://github.com/github/linguist/files/357182/2014-01-01-1.json.gz)

@igrigorik these are all uploaded now to `gs://githubarchive-bigquery/transformed-part-deux/`

**Comment by igrigorik** [comment] 2016-07-11 14:50
Hey guys, apologies, I've been out all last week. 

1. @bburky can you confirm that the file @arfon shared has all the data you're looking for?
1. Once we confirm I can cp the new files to the gs bucket and we'll have to rebuild the BQ tables once over. Anything else? @arfon do we need to update the transformer code in this repo to match your changes?

**Comment by arfon** [comment] 2016-07-11 19:51
> @arfon do we need to update the transformer code in this repo to match your changes?

I think we probably should for good housekeeping. There's now a set of 'expected' top-level fields that we [check against](https://github.com/arfon/gh_archive_parser/blob/master/event_transform.rb#L8-L21) and [warn](https://github.com/arfon/gh_archive_parser/blob/master/event_transform.rb#L88-L92) if there's something new.

Knowing what I know now I'd really like to completely rework this code but I'm a little short on time to work on this currently...

**Comment by bburky** [comment] 2016-07-11 22:14
Yes, it looks like the `url` field is showing up in `other` now. This should work fine. Thanks!

**Comment by igrigorik** [comment] 2016-07-14 02:06
> Knowing what I know now I'd really like to completely rework this code but I'm a little short on time to work on this currently... 

If you get around to it, I'd be happy to take a pull :-)

1. I've rebuilt the BQ tables for 2011-2015 based on reprocessed files -- thanks!
1. Monthly + Yearly summary tables have been updated based on (1)

Closing.

**Comment by arfon** [comment] 2016-07-14 02:41
> If you get around to it, I'd be happy to take a pull :-)

Will do.

**Closed** 2016-07-14 03:18 UTC

**Comment by bburky** [comment] 2016-07-14 03:35
Thanks for your fixing the data. I was able to use BigQuery to get the data I wanted.

If you ever want to get git reflog-like data out of the archive you can use the following query:

```sql
select *
from (
  select
    created_at,
    REGEXP_EXTRACT(repo_url, '/([^/]+)/[^/]+$') as user,
    REGEXP_EXTRACT(repo_url, '/[^/]+/([^/]+)$') as repo,
    JSON_EXTRACT_SCALAR(payload, "$.head") as head,
    IFNULL(
      JSON_EXTRACT_SCALAR(payload, "$.before"),
      REGEXP_EXTRACT(
        JSON_EXTRACT_SCALAR(other, "$.url"),
          '/compare/([A-Fa-f0-9]+)\\.\\.\\.[A-Fa-f0-9]+')
      ) as before,
  from TABLE_QUERY([githubarchive:month], 'true')
  where type = 'PushEvent'
) where
  -- Skip pushes with no change. `before` might be truncated though.
  LEFT(head, LENGTH(before)) != before;
```

(The regex isn't perfect, it really should end with a $, but I got tired of fighting regexes.)

This gets the before and after values of HEAD for each PushEvent from the GitHub archive. After processing 1.41TB of data (and $7 for the query), this returns a nice small 30GB of results that can then be analyzed.
