### ISSUE TITLE
Why there is no 'id' in the 'repository' part for many CreateEvents?

### ISSUE THREAD

**Issue by chengjun** [igrigorik/githubarchive.org#154] opened 2016-10-18 01:09 UTC
Why there is **no 'id' in the 'repository' part** for many CreateEvents? For example:

Your answer would be highly appreciated!

```
{u'actor': u'nervo',
 u'actor_attributes': {u'email': u'nervo@nervo.net',
  u'gravatar_id': u'cdc6346b8c4a2dd90e7cb6242b15b6a8',
  u'login': u'nervo',
  u'type': u'User'},
 u'created_at': u'2012/05/12 00:01:39 -0700',
 u'payload': {u'description': u'Simple and flexible HTML, CSS, and Javascript for popular user interface components and interactions.',
  u'master_branch': u'master',
  u'ref': None,
  u'ref_type': u'repository'},
 u'public': True,
 u'repository': {u'created_at': u'2012/05/12 00:01:39 -0700',
  u'description': u'Simple and flexible HTML, CSS, and Javascript for popular user interface components and interactions.',
  u'fork': False,
  u'forks': 1,
  u'has_downloads': True,
  u'has_issues': True,
  u'has_wiki': True,
  u'name': u'bootstrap',
  u'open_issues': 0,
  u'owner': u'nervo',
  u'private': False,
  u'pushed_at': u'2012/05/12 00:01:39 -0700',
  u'size': 0,
  u'url': u'https://github.com/nervo/bootstrap',
  u'watchers': 1},
 u'type': u'CreateEvent',
 u'url': u'https://github.com/nervo/bootstrap'}
```

**Comment by igrigorik** [comment] 2016-10-20 21:32
That's a great question.. to which I don't know the answer. Someone from GitHub would have to answer this one.

/me looks at @arfon :)

**Comment by arfon** [comment] 2016-10-21 14:30
Hi @chengjun, I'm not exactly sure what's going on here but happy to take a look. Can you construct a query that demonstrates this issue? It looks like the event you're listing here is from 2012 sometime - do you know if this issue exists in later event data (e.g. from 2016).

**Comment by igrigorik** [comment] 2017-02-25 16:12
Dupe of https://github.com/igrigorik/githubarchive.org/issues/161, let's continue there.

**Closed by igrigorik** 2017-02-25 16:12 UTC
